// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwqfO9aqh1wulVwVmQV6DPCRLuwAlvwSg',
    appId: '1:620197735212:web:7bed1b46eb4a0b11d65a89',
    messagingSenderId: '620197735212',
    projectId: 'uas-pemob-8efc6',
    authDomain: 'uas-pemob-8efc6.firebaseapp.com',
    storageBucket: 'uas-pemob-8efc6.appspot.com',
    measurementId: 'G-S65L74D545',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEveeLhZV-5VE2SbDmyVjRgP2YNvKsWzU',
    appId: '1:620197735212:android:11bd86539d25df4bd65a89',
    messagingSenderId: '620197735212',
    projectId: 'uas-pemob-8efc6',
    storageBucket: 'uas-pemob-8efc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2pQRkjVDgLT6yNZvRduT3ju8JA5GI7w',
    appId: '1:620197735212:ios:c92975e40d4c428ed65a89',
    messagingSenderId: '620197735212',
    projectId: 'uas-pemob-8efc6',
    storageBucket: 'uas-pemob-8efc6.appspot.com',
    iosClientId: '620197735212-gbg2fa94v0dhj4ej3eibr7lrn0kh2pgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2pQRkjVDgLT6yNZvRduT3ju8JA5GI7w',
    appId: '1:620197735212:ios:c92975e40d4c428ed65a89',
    messagingSenderId: '620197735212',
    projectId: 'uas-pemob-8efc6',
    storageBucket: 'uas-pemob-8efc6.appspot.com',
    iosClientId: '620197735212-gbg2fa94v0dhj4ej3eibr7lrn0kh2pgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
